routes/web.php
<?php

//Route::view('test','site.pages.jobs.vacant_jobs.create');
Route::group(
	[
		'prefix' => LaravelLocalization::setLocale(),
		'middleware' => ['localeSessionRedirect', 'localizationRedirect', 'localeViewPath']
	],
	function () {
		
		// Dashboard (Has Role)
		Route::get('dashboard/login', "Auth\LoginController@showLoginForm")->name("dashboard.login");
		Route::post('dashboard/login', "Auth\LoginController@login")->name("dashboard.post_login");
		Route::get('dashboard/logout', "Auth\LoginController@logout")->name("dashboard.logout");

		Route::post('setPassword', "Auth\LoginController@storePassword")->name('setPassword');
		Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.reset');
		Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
		Route::get('password/reset_form/{token?}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset_view');
		Route::post('password/reset_mobile', 'Auth\ResetPasswordController@resetMobile')->name('password.resetToNewMobile');
		Route::post('password/reset', 'Auth\ResetPasswordController@reset')->name('password.resetToNew');

		Route::get('/', 'Website\HomeController@index')->name('website.home');

	}
);

app/Models/Country.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Astrotomic\Translatable\Contracts\Translatable as TranslatableContract;
use Astrotomic\Translatable\Translatable;
use App\Scopes\RoleScope;

class Country extends Model implements TranslatableContract
{
    use Translatable;

    protected $guarded = ['id', 'created_at', 'updated_at', 'deleted_at'];
    public $translatedAttributes = ['name', 'currency'];

    public function cities()
    {
        return $this->hasMany(City::class);
    }

    protected static function boot()
    {
        parent::boot();
        static::saved(function ($data) {
            if (request()->hasFile('flag')) {
                if ($data->image()->exists()) {
                    $image = \App\Http\Controllers\General\ImageController::delete_single_file($data->image->image, 'app/public/uploads/country');
                    AppImage::where(['option' => 'flag', 'app_imageable_type' => 'App\Models\Country', 'app_imageable_id' => $data->id, 'image' => $data->image->image])->delete();
                }
                $image = \App\Http\Controllers\General\ImageController::upload_single_file(request()->flag, 'app/public/uploads/country');
                $data->image()->create(['image' => $image, 'option' => 'flag']);
            }
        });
    }

    public function delete()
    {
        if ($this->image()->exists()) {
            if (file_exists(storage_path('app/public/uploads/country' . "/" . $this->image->image))) {
                \App\Http\Controllers\General\ImageController::delete_single_file($this->image->image, 'app/public/uploads/country');
            }
            AppImage::where(['app_imageable_type' => 'App\Models\Country', 'app_imageable_id' => $this->id, 'image' => $this->image->image])->delete();
        }
        parent::delete();
    }

    public function image()
    {
        return $this->morphOne(AppImage::class, 'app_imageable');
    }

    public function getFlagUrlAttribute()
    {
        if ($this->image()->exists()) {
            if (!file_exists(storage_path('app/public/uploads/country' . "/" . $this->image->image))) {
                return asset('storage/uploads/default.png');
            }
            return asset('storage/uploads/country') . '/' . $this->image->image;
        } else {
            return asset('storage/uploads/default.png');
        }
    }
}

app/Http/Controllers/Dashboard/AdController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Models\{AdSponsor, Sponsor};
use App\Http\Requests\Dashboard\Ad\AdRequest;
use Illuminate\Http\Request;

class AdController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data['ads'] = AdSponsor::latest()->paginate(200);
        return view('dashboard.ad.index', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data['sponsors'] = Sponsor::get()->pluck('name', 'id');
        return view('dashboard.ad.create', $data);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(AdRequest $request)
    {
        \DB::beginTransaction();
        try {
            $ad = AdSponsor::create(array_except($request->validated(), ['file', 'file_type']));
            \DB::commit();
        } catch (Exception $e) {
            \DB::rollback();
            dd($e);
            return redirect()->route('dashboard.client.create')
                ->with('message', trans('dash.messages.something_went_wrong_please_try_again'))
                ->with('class', 'warning')->withInput();
        }
        return redirect()->route('dashboard.ad.index')->with('class', 'success')->with('message', trans('dash.messages.added_successfully'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if (!AdSponsor::find($id)) {
            return redirect()->route('dashboard.ad.index')->with('class', 'danger')->with('message', trans('dash.messages.try_2_access_not_found_content'));
        }
        $data['sponsors'] = Sponsor::get()->pluck('name', 'id');
        $data['ad'] = AdSponsor::find($id);
        return view('dashboard.ad.edit', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(AdRequest $request, $id)
    {
        if (!AdSponsor::find($id)) {
            return redirect()->route('dashboard.ad.index')->with('class', 'danger')->with('message', trans('dash.messages.try_2_access_not_found_content'));
        }
        $ad = AdSponsor::find($id);
        $ad->update(array_except($request->validated(), ['file', 'file_type']));
        return redirect()->route('dashboard.ad.index')->with('class', 'success')->with('message', trans('dash.messages.updated_successfully'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if (!AdSponsor::find($id)) {
            $response = ['status' => 'false', 'message' => trans('dash.messages.try_2_access_not_found_content')];
            return $response;
        }
        $ad = AdSponsor::find($id)->forceDelete();
        return ['status' => 'true', 'message' => trans('dash.messages.deleted_successfully')];
    }
}

app/Http/Controllers/Dashboard/AdminController.php
<?php

namespace App\Http\Controllers\Dashboard;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use DB, Auth;
use App\Models\User;
use App\Models\Role;
use App\Http\Requests\Dashboard\Admin\AdminRequest;

class AdminController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data['admins'] = User::where('type', 'admin')->latest()->get();
        return view('dashboard.admins.index', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $this->data['roles'] = Role::get()->pluck('name', 'id');
        $this->data['last_admins'] = User::orderBy('id', 'desc')->where('type', 'admin')->take(10)->get();
        return view('dashboard.admins.create', $this->data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(AdminRequest $request)
    {
        DB::beginTransaction();
        try {
            $admin = User::create(array_except($request->validated(), ['avatar']) + ['type' => 'admin']);
            DB::commit();
        } catch (Exception $e) {
            DB::rollback();
            return redirect()->route('dashboard.admin.create')
                ->with('message', trans('dash.messages.something_went_wrong_please_try_again'))
                ->with('class', 'warning')
                ->withInput($request->validated());
        }
        return redirect()->route('dashboard.admin.index')->with('class', 'success')->with('message', trans('dash.messages.added_successfully'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    { }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if (!User::where('type', 'admin')->find($id)) {
            return redirect()->route('dashboard.admin.index')->with('class', 'danger')->with('message', trans('dash.messages.try_2_access_not_found_content'));
        }
        $this->data['admin'] = User::where('type', 'admin')->find($id);
        $this->data['roles'] = Role::get()->pluck('name', 'id');
        $this->data['last_admins'] = User::orderBy('id', 'desc')->where('type', 'admin')->take(10)->get();
        return view('dashboard.admins.edit', $this->data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(AdminRequest $request, $id)
    {
        if (!User::where('type', 'admin')->find($id)) {
            return redirect()->route('dashboard.admin.index')->with('class', 'danger')->with('message', trans('dash.messages.try_2_access_not_found_content'));
        }
        DB::beginTransaction();
        try {
            $admin = User::find($id)->update(array_except($request->validated(), ['avatar']));
            DB::commit();
        } catch (Exception $e) {
            DB::rollback();
            return redirect()->route('dashboard.admin.edit', $id)
                ->with('message', trans('dash.messages.something_went_wrong_please_try_again'))
                ->with('class', 'warning')
                ->withInput($request->validated());
        }
        return redirect()->route('dashboard.admin.index')->with('class', 'success')->with('message', trans('dash.messages.updated_successfully'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if (!User::where('type', 'admin')->find($id)) {
            $response = ['status' => 'false', 'message' => trans('dash.messages.try_2_access_not_found_content')];
            return $response;
        }
        $user = User::where('type', 'admin')->find($id);
        $user->forceDelete();
        return ['status' => 'true', 'message' => trans('dash.messages.deleted_successfully')];
    }

    public function chat()
    {
        return view('dashboard.admins.chat');
    }
}

app/Http/Controllers/Dashboard/AuthController.php
<?php

namespace App\Http\Controllers\Dashboard;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\User;
use Hash;
use App\Http\Requests\Dashboard\Auth\UpdateProfileData;
use App\Http\Requests\Dashboard\Auth\UpdatePassword;

class AuthController extends Controller
{
    public function signin_view()
    {
        return view('dashboard.auth.login');
    }

    public function signin(Request $request)
    {
        if ($request->email && $request->password) {
            if (auth()->attempt(['email' => $request->email, 'password' => $request->password, 'type' => 'admin'], true)) {
                return redirect()->route('dashboard.home');
            } else {
                $request->session()->flash('warning', trans('dashboard.email_or_password_invalid'));
                return redirect()->route('dashboard.login')
                    ->with('message', trans('dash.messages.data_invalid'))
                    ->with('class', 'danger');
            }
        } else {
            return redirect()->route('dashboard.login')
                ->with('message', trans('dash.messages.data_not_completed'))
                ->with('class', 'danger');
        }
    }

    public function signout()
    {
        auth()->logout();
        return redirect()->route('dashboard.login')
            ->with('message', trans('dash.messages.logged_out_successfully'))
            ->with('class', 'success');
    }

    public function profile()
    {
        return view('dashboard.auth.profile');
    }

    public function update(UpdateProfileData $request)
    {
        User::find(auth()->id())->update(array_except($request->validated(), ['avatar']));
        return redirect()->route('dashboard.admin.profile')->with('class', 'success')->with('message', trans('dash.messages.updated_successfully'));
    }

    public function update_password(UpdatePassword $request)
    {
        if (Hash::check($request->old_password, auth()->user()->getAuthPassword())) {
            User::find(auth()->id())->update(['password' => $request->password]);
            return redirect()->route('dashboard.admin.profile')->with('class', 'success')->with('message', trans('dash.messages.updated_password_successfully'));
        } else {
            return back()->with('message', trans('dash.messages.wrong_password'))->with('class', 'danger');
        }
    }
}

app/Http/Controllers/Dashboard/ContactController.php
<?php

namespace App\Http\Controllers\Dashboard;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Contact;
use App\Models\User;
use Mail;

class ContactController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $this->data['contacts'] = Contact::when($request->status,function($q) use($request) {
            $q->where('read_at', null);
        })->latest()->get();
        return view('dashboard.contact.index', $this->data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        if (!Contact::find($id)) {
            return redirect()->route('dashboard.contact.index')->with('class', 'danger')->with('message', trans('dash.messages.try_2_access_not_found_content'));
        }
        $this->data['contact'] = Contact::find($id);
        $this->data['contact']->update(['read_at' => now()]);
        return view('dashboard.contact.show', $this->data);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if (!Contact::find($id)) {
            $response = ['status' => 'false', 'message' => trans('dash.messages.try_2_access_not_found_content')];
            return $response;
        }
        $contact = Contact::find($id)->forceDelete();
        return ['status' => 'true', 'message' => trans('dash.messages.deleted_successfully')];
    }

    public function reply(Request $request)
    {
        $user = User::find($request->email);
        Mail::send('mails.contact', $request->all(), function ($message) use ($request) {
            $message->from(settings('formal_email_message'), settings('project_name_' . app()->getLocale()));
            $message->sender(settings('formal_email_message'), settings('project_name_' . app()->getLocale()));
        
            $message->to($request->email, '');
    
            $message->replyTo(settings('formal_email_message'), settings('project_name_' . app()->getLocale()));
        
            $message->subject('رسالة إدارية');
        
            $message->priority(1);
        
            // $message->attach('pathToFile');
        });
        // ::to($user)->send(new ReplyContact($request->all()));
        return redirect()->route('dashboard.contact.index')->with('class', 'success')->with('message', trans('dash.messages.sent_successfully'));
    }
}

resources/views/dashboard/city/create.blade.php
@extends('dashboard.layout')
@section('page_title')
{{ trans('dash.city.add_new_city') }}
@endsection
@section('sidebar_title')
    <a href="{{ route('dashboard.city.index') }}" class="breadcrumb-item">{{ trans('dash.city.cities') }}</a>
    <span class="breadcrumb-item active">{{ trans('dash.city.add_new_city') }}</span>
@endsection
@section('content')
        <div class="card">
            <div class="card-header header-elements-inline">
                <h5 class="card-title">{{ trans('dash.city.city_data') }}</h5>
            </div>
            <div class="card-body">
                {!! Form::open(['route' => 'dashboard.city.store' , 'method' => "POST" , 'files' => true , 'data-fouc']) !!}
                    @include('dashboard.city.form')
				{!! Form::close() !!}
            </div>
        </div>
@endsection

resources/views/dashboard/city/edit.blade.php
@extends('dashboard.layout')
@section('page_title')
{{ trans('dash.city.edit_city_data') }}
@endsection
@section('sidebar_title')
    <a href="{{ route('dashboard.city.index') }}" class="breadcrumb-item">{{ trans('dash.city.cities') }}</a>
    <span class="breadcrumb-item active">{{ trans('dash.city.edit_city_data') }}</span>
@endsection
@section('content')
        <div class="card">
            <div class="card-header header-elements-inline">
                <h5 class="card-title">{{ trans('dash.city.edit_city_data') }} : {{ $city['name_' . app()->getLocale()] }}</h5>
            </div>
            <div class="card-body">
                {!! Form::model($city, ['route' => ['dashboard.city.update', $city->id] , 'method' => "PUT" , 'files' => true , 'data-fouc']) !!}
                    @include('dashboard.city.form')
				{!! Form::close() !!}
            </div>
        </div>
@endsection

resources/views/dashboard/city/form.blade.php
@section('file_scripts')
    <script src="{{ asset('assets/global') }}/js/plugins/forms/wizards/steps.min.js"></script>
	<script src="{{ asset('assets/global') }}/js/plugins/forms/styling/uniform.min.js"></script>
    <script src="{{ asset('assets/global') }}/js/plugins/extensions/jquery_ui/interactions.min.js"></script>
	<script src="{{ asset('assets/global') }}/js/plugins/forms/selects/select2.min.js"></script>
    <script src="{{ asset('assets/global') }}/js/plugins/tables/datatables/datatables.min.js"></script>

    <script src="{{ asset('assets/global') }}/js/plugins/forms/inputs/inputmask.js"></script>
	<script src="{{ asset('assets/global') }}/js/plugins/forms/validation/validate.min.js"></script>
	<script src="{{ asset('assets/global') }}/js/plugins/extensions/cookie.js"></script>
@endsection

@section('custom_scripts')
	<script src="{{ asset('assets/global') }}/js/demo_pages/form_layouts.js"></script>
    <script src="{{ asset('assets/global') }}/js/demo_pages/datatables_basic.js"></script>
    <script src="{{ asset('assets/global') }}/js/demo_pages/form_select2.js"></script>
    @if(LaravelLocalization::getCurrentLocaleDirection() == 'rtl')
        <script src="{{ asset('assets/global') }}/js/demo_pages/form_wizard_rtl.js"></script>
    @else
        <script src="{{ asset('assets/global') }}/js/demo_pages/form_wizard.js"></script>
    @endif
@endsection

@section('style')
<style>
    #pac-input{
        width: 390px;
        padding-right: 15px;
    }
</style>
@endsection

@foreach (config('translatable.locales') as $locale)
	{{-- <h6>{{ LaravelLocalization::getSupportedLocales()[$locale]['native'] }}</h6> --}}
	<fieldset class="content-group">
		<div class="form-group row">
            <label class="col-form-label col-lg-3">{{ trans('dash.'.$locale.'.name') }} :</label>
            <div class="col-lg-9">
                {!! Form::text($locale."[name]", isset($city) ? $city->translate($locale)->name : null, ['class' => 'form-control' , 'placeholder' => trans('dash.'.$locale.'.name')]) !!}
            </div>
        </div>
	</fieldset>
@endforeach
{{-- <h6>{{ trans('dash.form.public_data') }}</h6> --}}
<fieldset>
    <div class="form-group row">
        <label class="col-form-label col-lg-3">{{ trans('dash.country.countries') }} :</label>
        <div class="col-lg-9">
            {!! Form::select('country_id', $countries, null, ['class' => 'form-control' , 'placeholder' => trans('dash.country.countries')]) !!}
        </div>
    </div>
	<div class="form-group row">
        <label class="col-form-label col-lg-3">{{ trans('dash.city.postal_code') }} :</label>
        <div class="col-lg-9">
            {!! Form::number('postal_code', isset($city) ? $city->postal_code : null, ['class' => 'form-control' , 'placeholder' => trans('dash.city.postal_code')]) !!}
        </div>
    </div>
	<div class="form-group row">
        <label class="col-form-label col-lg-3">{{ trans('dash.city.short_cut') }} :</label>
        <div class="col-lg-9">
            {!! Form::text('short_cut', isset($city) ? $city->short_cut : null, ['class' => 'form-control' , 'placeholder' => trans('dash.city.short_cut')]) !!}
        </div>
    </div>
</fieldset>
<legend class="font-weight-semibold text-uppercase font-size-sm"></legend>
<div class="text-right">
    <button type="submit" class="btn btn-success"><i class="icon-paperplane mr-2"></i>{{ trans('dash.buttons.submit_back_to_list') }}</button>
</div>

resources/views/dashboard/city/index.blade.php
@extends('dashboard.layout')
    @section('file_scripts')
    <script src="{{ asset('assets/global') }}/js/plugins/media/fancybox.min.js"></script>
    <script src="{{ asset('assets/global') }}/js/plugins/forms/styling/uniform.min.js"></script>
    <script src="{{ asset('assets/global') }}/js/plugins/tables/datatables/datatables.min.js"></script>
    <script src="{{ asset('assets/global') }}/js/plugins/tables/datatables/extensions/buttons.min.js"></script>
    <script src="{{ asset('assets/global') }}/js/plugins/forms/selects/select2.min.js"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
@endsection

@section('custom_scripts')
    <script src="{{ asset('assets') }}/global/js/demo_pages/form_select2.js"></script>
    <script src="{{ asset('assets/global') }}/js/demo_pages/datatables_extension_buttons_init.js"></script>
    <script src="{{ asset('assets/global') }}/js/demo_pages/gallery_library.js"></script>
@endsection
@section('page_title')
    {{ trans('dash.city.cities') }}
@endsection
@section('sidebar_title')
    <span class="breadcrumb-item active">{{ trans('dash.city.cities') }}</span>
@endsection
@section('content')
<!-- Basic initialization -->
<div class="card">
    <div class="card-header header-elements-inline">
        <h5 class="card-title">{{ trans('dash.city.cities') }}</h5>
        <div class="header-elements">
            <div class="list-icons">
                <a href="{{ route('dashboard.city.create') }}" class="btn btn-success btn-labeled btn-labeled-left"><b><i class="icon-plus2"></i></b>{{ trans('dash.city.add_new_city') }}</a>
            </div>
        </div>
    </div>
    <div class="card-body">
        <hr>
        {!! Form::open(['route' => 'dashboard.city.index' , 'method' => 'GET']) !!}
        <div class="form-group row pt-3">
            <div class="col-md-11">
                {!! Form::select("country_id",$countries, null, ['class' => 'form-control select-search' , 'placeholder' => trans('dash.country.country')]) !!}
            </div>
            <div class="col-md-1 text-center">
                <button type="submit" class="btn btn-info btn-sm">{!! trans('dash.buttons.send') !!}</button>
            </div>
        </div>
        {!! Form::close() !!}
        <div class="d-flex justify-content-center">
            {!! $cities->links() !!}
        </div>
        <table class="table datatable-button-init-basic">
            <thead>
                <tr class="text-center">
                    <th>#</th>
                    <th>{{ trans('dash.country.flag') }}</th>
                    <th>{{ trans('dash.country.name') }}</th>
                    <th>{{ trans('dash.city.name') }}</th>
                    <th>{{ trans('dash.table.created_at') }}</th>
                    <th>{{ trans('dash.table.action') }}</th>
                </tr>
            </thead>
            <tbody>
                @foreach($cities as $city)
                <tr class="text-center" id="row_{{ $city->id }}">
                    <td>{{ $loop->iteration }}</td>
                    <td>
                        <a href="{{ $city->country->flag_url }}" data-popup="lightbox">
                            <img src="{{ $city->country->flag_url }}" alt="" width="80" height="70" class="img-preview rounded">
                        </a>
                    </td>
                    <td>{{ $city->country->name }}</td>
                    <td>{{ $city->name }}</td>
                    <td>{{ $city->created_at->diffforHumans() }}</td>
                    <td>
                        <div class="list-icons">
                            <div class="list-icons-item dropdown">
                                <a href="#" class="list-icons-item caret-0 dropdown-toggle" data-toggle="dropdown">
                                    <i class="icon-menu9"></i>
                                </a>
                                <div class="dropdown-menu dropdown-menu-right">
                                    <a href="{{ route('dashboard.city.edit', $city->id) }}" class="dropdown-item"><i class="icon-pencil7"></i>{{ trans('dash.actions.edit') }}</a>
                                    {{--  <a href="{{ route('dashboard.city.show', $city->id) }}" class="dropdown-item"><i class="icon-eye"></i>{{ trans('dash.actions.show') }}</a>  --}}
                                    <div class="dropdown-divider"></div>
                                    <a onclick="sweet_delete('{{ route('dashboard.city.destroy', $city->id) }}', {{ $city->id }} )" class="dropdown-item"><i class="icon-bin"></i>{{ trans('dash.actions.delete') }}</a>
                                </div>
                            </div>
                        </div>
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
        <div class="d-flex justify-content-center">
            {!! $cities->links() !!}
        </div>
    </div>
</div>
<!-- /basic initialization -->
@include('dashboard.parts.delete_alert')
@endsection

resources/views/dashboard/city/last_created.blade.php
<div class="col-md-5">
    <div class="card">
        <div class="card-header header-elements-inline">
            <h5 class="card-title">{{ trans('dash.city.latest_cities') }}</h5>                
        </div>
        <table class="table datatable-basic">
            <thead>
                <tr class="text-center">
                    <th>#</th>
                    <th>{{ trans('dash.country.country') }}</th>
                    <th>{{ trans('dash.city.city') }}</th>
                    <th>{{ trans('dash.table.created_at') }}</th>
                </tr>
            </thead>
            <tbody>
                @foreach($latest_cities as $city)
                    <tr class="text-center">
                        <td>{{ $loop->iteration }}</td>
                        <td>{{ $city->country->name }}</td>
                        <td>{{ $city->name }}</td>
                        <td>{{ $city->created_at->diffforHumans() }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>
</div>