routes/web.php
<?php

//Route::view('test','site.pages.jobs.vacant_jobs.create');
Route::group(
	[
		'prefix' => LaravelLocalization::setLocale(),
		'middleware' => ['localeSessionRedirect', 'localizationRedirect', 'localeViewPath']
	],
	function () {
		
		// Dashboard (Has Role)
		Route::get('dashboard/login', "Auth\LoginController@showLoginForm")->name("dashboard.login");
		Route::post('dashboard/login', "Auth\LoginController@login")->name("dashboard.post_login");
		Route::get('dashboard/logout', "Auth\LoginController@logout")->name("dashboard.logout");

		Route::post('setPassword', "Auth\LoginController@storePassword")->name('setPassword');
		Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.reset');
		Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
		Route::get('password/reset_form/{token?}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset_view');
		Route::post('password/reset_mobile', 'Auth\ResetPasswordController@resetMobile')->name('password.resetToNewMobile');
		Route::post('password/reset', 'Auth\ResetPasswordController@reset')->name('password.resetToNew');

		Route::get('/', 'Website\HomeController@index')->name('website.home');

	}
);

app/Models/Movie.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Movie extends Model
{
    protected $guarded = ['id', 'created_at', 'updated_at', 'deleted_at'];

    public function getMovieDetailAttribute()
    {
        return json_decode($this->attributes['movie_data']);
    }
}

app/Http/Controllers/Dashboard/AdController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Models\{AdSponsor, Sponsor};
use App\Http\Requests\Dashboard\Ad\AdRequest;
use Illuminate\Http\Request;

class AdController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data['ads'] = AdSponsor::latest()->paginate(200);
        return view('dashboard.ad.index', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data['sponsors'] = Sponsor::get()->pluck('name', 'id');
        return view('dashboard.ad.create', $data);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(AdRequest $request)
    {
        \DB::beginTransaction();
        try {
            $ad = AdSponsor::create(array_except($request->validated(), ['file', 'file_type']));
            \DB::commit();
        } catch (Exception $e) {
            \DB::rollback();
            dd($e);
            return redirect()->route('dashboard.client.create')
                ->with('message', trans('dash.messages.something_went_wrong_please_try_again'))
                ->with('class', 'warning')->withInput();
        }
        return redirect()->route('dashboard.ad.index')->with('class', 'success')->with('message', trans('dash.messages.added_successfully'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if (!AdSponsor::find($id)) {
            return redirect()->route('dashboard.ad.index')->with('class', 'danger')->with('message', trans('dash.messages.try_2_access_not_found_content'));
        }
        $data['sponsors'] = Sponsor::get()->pluck('name', 'id');
        $data['ad'] = AdSponsor::find($id);
        return view('dashboard.ad.edit', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(AdRequest $request, $id)
    {
        if (!AdSponsor::find($id)) {
            return redirect()->route('dashboard.ad.index')->with('class', 'danger')->with('message', trans('dash.messages.try_2_access_not_found_content'));
        }
        $ad = AdSponsor::find($id);
        $ad->update(array_except($request->validated(), ['file', 'file_type']));
        return redirect()->route('dashboard.ad.index')->with('class', 'success')->with('message', trans('dash.messages.updated_successfully'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if (!AdSponsor::find($id)) {
            $response = ['status' => 'false', 'message' => trans('dash.messages.try_2_access_not_found_content')];
            return $response;
        }
        $ad = AdSponsor::find($id)->forceDelete();
        return ['status' => 'true', 'message' => trans('dash.messages.deleted_successfully')];
    }
}

app/Http/Controllers/Dashboard/AdminController.php
<?php

namespace App\Http\Controllers\Dashboard;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use DB, Auth;
use App\Models\User;
use App\Models\Role;
use App\Http\Requests\Dashboard\Admin\AdminRequest;

class AdminController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data['admins'] = User::where('type', 'admin')->latest()->get();
        return view('dashboard.admins.index', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $this->data['roles'] = Role::get()->pluck('name', 'id');
        $this->data['last_admins'] = User::orderBy('id', 'desc')->where('type', 'admin')->take(10)->get();
        return view('dashboard.admins.create', $this->data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(AdminRequest $request)
    {
        DB::beginTransaction();
        try {
            $admin = User::create(array_except($request->validated(), ['avatar']) + ['type' => 'admin']);
            DB::commit();
        } catch (Exception $e) {
            DB::rollback();
            return redirect()->route('dashboard.admin.create')
                ->with('message', trans('dash.messages.something_went_wrong_please_try_again'))
                ->with('class', 'warning')
                ->withInput($request->validated());
        }
        return redirect()->route('dashboard.admin.index')->with('class', 'success')->with('message', trans('dash.messages.added_successfully'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    { }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if (!User::where('type', 'admin')->find($id)) {
            return redirect()->route('dashboard.admin.index')->with('class', 'danger')->with('message', trans('dash.messages.try_2_access_not_found_content'));
        }
        $this->data['admin'] = User::where('type', 'admin')->find($id);
        $this->data['roles'] = Role::get()->pluck('name', 'id');
        $this->data['last_admins'] = User::orderBy('id', 'desc')->where('type', 'admin')->take(10)->get();
        return view('dashboard.admins.edit', $this->data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(AdminRequest $request, $id)
    {
        if (!User::where('type', 'admin')->find($id)) {
            return redirect()->route('dashboard.admin.index')->with('class', 'danger')->with('message', trans('dash.messages.try_2_access_not_found_content'));
        }
        DB::beginTransaction();
        try {
            $admin = User::find($id)->update(array_except($request->validated(), ['avatar']));
            DB::commit();
        } catch (Exception $e) {
            DB::rollback();
            return redirect()->route('dashboard.admin.edit', $id)
                ->with('message', trans('dash.messages.something_went_wrong_please_try_again'))
                ->with('class', 'warning')
                ->withInput($request->validated());
        }
        return redirect()->route('dashboard.admin.index')->with('class', 'success')->with('message', trans('dash.messages.updated_successfully'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if (!User::where('type', 'admin')->find($id)) {
            $response = ['status' => 'false', 'message' => trans('dash.messages.try_2_access_not_found_content')];
            return $response;
        }
        $user = User::where('type', 'admin')->find($id);
        $user->forceDelete();
        return ['status' => 'true', 'message' => trans('dash.messages.deleted_successfully')];
    }

    public function chat()
    {
        return view('dashboard.admins.chat');
    }
}

app/Http/Controllers/Dashboard/AuthController.php
<?php

namespace App\Http\Controllers\Dashboard;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\User;
use Hash;
use App\Http\Requests\Dashboard\Auth\UpdateProfileData;
use App\Http\Requests\Dashboard\Auth\UpdatePassword;

class AuthController extends Controller
{
    public function signin_view()
    {
        return view('dashboard.auth.login');
    }

    public function signin(Request $request)
    {
        if ($request->email && $request->password) {
            if (auth()->attempt(['email' => $request->email, 'password' => $request->password, 'type' => 'admin'], true)) {
                return redirect()->route('dashboard.home');
            } else {
                $request->session()->flash('warning', trans('dashboard.email_or_password_invalid'));
                return redirect()->route('dashboard.login')
                    ->with('message', trans('dash.messages.data_invalid'))
                    ->with('class', 'danger');
            }
        } else {
            return redirect()->route('dashboard.login')
                ->with('message', trans('dash.messages.data_not_completed'))
                ->with('class', 'danger');
        }
    }

    public function signout()
    {
        auth()->logout();
        return redirect()->route('dashboard.login')
            ->with('message', trans('dash.messages.logged_out_successfully'))
            ->with('class', 'success');
    }

    public function profile()
    {
        return view('dashboard.auth.profile');
    }

    public function update(UpdateProfileData $request)
    {
        User::find(auth()->id())->update(array_except($request->validated(), ['avatar']));
        return redirect()->route('dashboard.admin.profile')->with('class', 'success')->with('message', trans('dash.messages.updated_successfully'));
    }

    public function update_password(UpdatePassword $request)
    {
        if (Hash::check($request->old_password, auth()->user()->getAuthPassword())) {
            User::find(auth()->id())->update(['password' => $request->password]);
            return redirect()->route('dashboard.admin.profile')->with('class', 'success')->with('message', trans('dash.messages.updated_password_successfully'));
        } else {
            return back()->with('message', trans('dash.messages.wrong_password'))->with('class', 'danger');
        }
    }
}

app/Http/Controllers/Dashboard/CityController.php
<?php

namespace App\Http\Controllers\Dashboard;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\{
    City, Country, Package, Store, Street, User
};
use App\Http\Requests\Dashboard\City\{CityRequest};

class CityController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $this->data['cities'] = City::when($request->country_id,function($q)use($request){
            $q->where('country_id',$request->country_id);
        })->latest()->paginate(200);
        $this->data['countries'] = Country::get()->pluck('name', 'id');
        return view('dashboard.city.index', $this->data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $this->data['countries'] = Country::get()->pluck('name', 'id');
        $this->data['latest_cities'] = City::latest()->take(10)->get();
        return view('dashboard.city.create', $this->data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CityRequest $request)
    {
        $city = City::create($request->validated());
        return redirect()->route('dashboard.city.index')->with('class', 'success')->with('message', trans('dash.messages.added_successfully'));
    }



    public function show($id)
    {
        if (!City::find($id)) {
            return redirect()->route('dashboard.city.index')->with('class', 'danger')->with('message', trans('dash.messages.try_2_access_not_found_content'));
        }
        $this->data['city'] = City::find($id);

        $this->data['clients_count'] = User:: where('type', 'client')->where(['city_id' => $id])->count();

        return view('dashboard.city.show', $this->data);
    }


    public function edit($id)
    {
        if (!City::find($id)) {
            return redirect()->route('dashboard.city.index')->with('class', 'danger')->with('message', trans('dash.messages.try_2_access_not_found_content'));
        }
        $this->data['latest_cities'] = City::latest()->take(10)->get();
        $this->data['city'] = City::find($id);
        $this->data['countries'] = Country::get()->pluck('name', 'id');
        return view('dashboard.city.edit', $this->data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(CityRequest $request, $id)
    {
        if (!City::find($id)) {
            return redirect()->route('dashboard.city.edit', $id)->with('class', 'danger')->with('message', trans('dash.messages.try_2_access_not_found_content'));
        }
        City::find($id)->update($request->validated());
        return redirect()->route('dashboard.city.index')->with('class', 'success')->with('message', trans('dash.messages.updated_successfully'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if (!City::find($id)) {
            $response = ['status' => 'false', 'message' => trans('dash.messages.try_2_access_not_found_content')];
            return $response;
        }
        $city = City::find($id)->forceDelete();
        return ['status' => 'true', 'message' => trans('dash.messages.deleted_successfully')];
    }

    public function get_cities_by_country($country_id)
    {
        $cities = City::where('country_id', $country_id)->listsTranslations('name')->get()->pluck('name', 'id');
        $view = view('dashboard.city.ajax.get_cities', compact('cities'))->render();
        return response()->json(['value' => 1, 'view' => $view]);
    }


    public function getCities(Request $request)
    {

        $country = Country::find($request->country_id);

        if(!$country) return response()->json(['status' => false], 500);

        return response()->json(['cities' => $country->cities, 'status' => true], 200);
    }
}

app/Http/Controllers/Dashboard/SupportController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class SupportController extends Controller
{
    //
}

app/Http/Controllers/Website/HomeController.php
<?php

namespace App\Http\Controllers\Website;

use App\Http\Controllers\Controller;
use App\Models\{City, Country};
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Cookie;

class HomeController extends Controller
{
    public function index()
    {
        //
    }
}

resources/views/dashboard/home/index.blade.php
@extends('dashboard.layout')
@section('style')
	<style>
		.scroll-y{
			height: 425px;
			overflow-y: scroll;
			overflow-x: hidden;
		}
		.scroll-y::-webkit-scrollbar {
			width: 5px;
		}
		.scroll-y::-webkit-scrollbar-thumb {
			background-color: #2196f3;
		}
	</style>
@endsection
@section('file_scripts')
	<!-- Theme JS files -->
	<script src="{{ asset('assets/global') }}/js/plugins/visualization/echarts/echarts.min.js"></script>
	<script src="{{ asset('assets/global') }}/js/plugins/visualization/d3/d3.min.js"></script>
	<script src="{{ asset('assets/global') }}/js/plugins/visualization/d3/d3_tooltip.js"></script>
	<script src="{{ asset('assets/global') }}/js/plugins/forms/styling/switchery.min.js"></script>
	<script src="{{ asset('assets/global') }}/js/plugins/forms/selects/bootstrap_multiselect.js"></script>
	<script src="{{ asset('assets/global') }}/js/plugins/ui/moment/moment.min.js"></script>
	<script src="{{ asset('assets/global') }}/js/plugins/pickers/daterangepicker.js"></script>
	<script src="{{ asset('assets/global') }}/js/plugins/media/fancybox.min.js"></script>
	<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
	<!-- /theme JS files -->
@endsection
@section('custom_scripts')
	<script src="{{ asset('assets/global') }}/js/demo_pages/dashboard.js"></script>
	<script src="{{ asset('assets/global') }}/js/demo_pages/gallery_library.js"></script>
	@include('dashboard.home.custom_charts')
	<script>
		document.addEventListener('DOMContentLoaded', function() {
			UsersChart.init();
			PostsChart.init();
		});
	</script>
@endsection
@section('page_title')
    {{ trans('dash.navbar.main_page') }}
@endsection
@section('content')
    <div class="row">
        <div class="col-lg-9">
            <div class="row">
                <div class="col-lg-3">
                    <a href="{{ route('dashboard.permission.index') }}">
                        <div class="card bg-{{ random_colors() }}">
                            <div class="card-body">
                                <div class="d-flex">
                                    <h3 class="font-weight-semibold mb-0">{{ $permissions_count }}</h3>
                                </div>
                                <div>
                                    {{ trans('dash.home.permissions_count') }}
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-lg-3">
                    <a href="{{ route('dashboard.admin.index') }}">
                        <div class="card bg-{{ random_colors() }}">
                            <div class="card-body">
                                <div class="d-flex">
                                    <h3 class="font-weight-semibold mb-0">{{ $admins_count }}</h3>
                                </div>
                                <div>
                                    {{ trans('dash.home.admins_count') }}
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-lg-3">
                    <a href="{{ route('dashboard.client.index') }}">
                        <div class="card bg-{{ random_colors() }}">
                            <div class="card-body">
                                <div class="d-flex">
                                    <h3 class="font-weight-semibold mb-0">{{ $clients_count }}</h3>
                                </div>
                                <div>
                                    {{ trans('dash.home.clients_count') }}
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-lg-3">
                    <a href="{{ route('dashboard.contact.index') }}?is_seen=unseen">
                        <div class="card bg-{{ random_colors() }}">
                            <div class="card-body">
                                <div class="d-flex">
                                    <h3 class="font-weight-semibold mb-0">{{ $contacts_count }}</h3>
                                </div>
                                <div>
                                    {{ trans('dash.home.unseen_contacts_count') }}
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-3">
                    <a href="">
                        <div class="card bg-{{ random_colors() }}">
                            <div class="card-body">
                                <div class="d-flex">
                                    <h3 class="font-weight-semibold mb-0">{{ $today_posts_count }}</h3>
                                </div>
                                <div>
                                    {{ trans('dash.home.today_posts_count') }}
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-lg-3">
                    <a href="">
                        <div class="card bg-{{ random_colors() }}">
                            <div class="card-body">
                                <div class="d-flex">
                                    <h3 class="font-weight-semibold mb-0">{{ $posts_count }}</h3>
                                </div>
                                <div>
                                    {{ trans('dash.home.posts_count') }}
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-lg-3">
                    <a href="{{ route('dashboard.city.index') }}">
                        <div class="card bg-{{ random_colors() }}">
                            <div class="card-body">
                                <div class="d-flex">
                                    <h3 class="font-weight-semibold mb-0">{{ $cities_count }}</h3>
                                </div>
                                <div>
                                    {{ trans('dash.home.cities_count') }}
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-lg-3">
                    <a href="{{ route('dashboard.country.index') }}">
                        <div class="card bg-{{ random_colors() }}">
                            <div class="card-body">
                                <div class="d-flex">
                                    <h3 class="font-weight-semibold mb-0">{{ $countries_count }}</h3>
                                </div>
                                <div>
                                    {{ trans('dash.home.countries_count') }}
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
            </div>
        </div>
        <div class="col-lg-3">
            <div class="card my-card border-right-2 border-left-2 border-right-primary border-left-primary">
                <div class="card-header header-elements-inline">
                    <h6 class="card-title">{{ trans('dash.home.movie.popular_movies') }}</h6>
                </div>
                <div class="card-body pb-0">
                    <div class="row">
                        <div class="col-xl-12">
                            @foreach($movies as $movie)
                                <div class="media flex-column flex-sm-row mt-0 mb-3">
                                    <div class="mr-sm-3 mb-2 mb-sm-0">
                                        <div class="card-img-actions">
                                            @if(isset($movie->movie_detail->poster_path))
                                                <a href="https://image.tmdb.org/t/p/w500{{ $movie->movie_detail->poster_path }}" data-popup="lightbox">
                                                    <img src="https://image.tmdb.org/t/p/w500{{ $movie->movie_detail->poster_path }}" alt="" class="img-fluid img-preview rounded">
                                                    <span class="card-img-actions-overlay card-img"><i class="icon-image icon-2x"></i></span>
                                                </a>
                                            @else
                                                <a href="{{ asset('storage/uploads/default.png') }}" data-popup="lightbox">
                                                    <img src="{{ asset('storage/uploads/default.png') }}" style="width: 53.33px; height: 79.98px" alt="" class="img-fluid img-preview rounded">
                                                    <span class="card-img-actions-overlay card-img"><i class="icon-image icon-2x"></i></span>
                                                </a>
                                            @endif
                                        </div>
                                    </div>
                                    <div class="media-body">
                                        <h6 class="media-title"><a href="#">{{ @$movie->movie_detail->original_title }}</a></h6>
                                        <ul class="list-inline list-inline-dotted text-muted mb-2">
                                            <li class="list-inline-item">{{ trans('dash.home.movie.counter') }} : {{ $movie->counter }}</li>
                                        </ul>
                                        <ul class="list-inline list-inline-dotted text-muted mb-2">
                                            <li class="list-inline-item">{{ trans('dash.home.movie.vote_average') }} : {{ @$movie->movie_detail->vote_average }}</li>
                                        </ul>
                                    </div>
                                </div>
                            @endforeach
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
	<div class="row">
		<div class="col-xl-12">
			<div class="card border-right-2 border-left-2 border-right-primary border-left-primary">
				<div class="card-body">
					<div class="chart-container">
						<div class="chart has-fixed-height" id="customers_chart"></div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-xl-12">
			<div class="card border-right-2 border-left-2 border-right-primary border-left-primary">
				<div class="card-body">
					<div class="chart-container">
						<div class="chart has-fixed-height" id="posts_chart"></div>
					</div>
				</div>
			</div>
		</div>
	</div>
    <style>
        .my-card{
            height: 390px;
            overflow-y: scroll;
        }
        .my-card::-webkit-scrollbar {
            width: 5px;
        }

        /* Track */
        .my-card::-webkit-scrollbar-track {
            box-shadow: inset 0 0 5px grey;
            border-radius: 10px;
        }

        /* Handle */
        .my-card::-webkit-scrollbar-thumb {
            background: #0aa7ef;
            border-radius: 10px;
        }

        /* Handle on hover */
        .my-card::-webkit-scrollbar-thumb:hover {
            background: #0aa7ef;
        }

    </style>
@endsection