routes/web.php
<?php

//Route::view('test','site.pages.jobs.vacant_jobs.create');
Route::group(
	[
		'prefix' => LaravelLocalization::setLocale(),
		'middleware' => ['localeSessionRedirect', 'localizationRedirect', 'localeViewPath']
	],
	function () {
		
		// Dashboard (Has Role)
		Route::get('dashboard/login', "Auth\LoginController@showLoginForm")->name("dashboard.login");
		Route::post('dashboard/login', "Auth\LoginController@login")->name("dashboard.post_login");
		Route::get('dashboard/logout', "Auth\LoginController@logout")->name("dashboard.logout");

		Route::post('setPassword', "Auth\LoginController@storePassword")->name('setPassword');
		Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.reset');
		Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
		Route::get('password/reset_form/{token?}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset_view');
		Route::post('password/reset_mobile', 'Auth\ResetPasswordController@resetMobile')->name('password.resetToNewMobile');
		Route::post('password/reset', 'Auth\ResetPasswordController@reset')->name('password.resetToNew');

		Route::get('/', 'Website\HomeController@index')->name('website.home');

	}
);

app/Models/AdSponsor.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class AdSponsor extends Model
{
    protected $guarded = ['id', 'created_at', 'updated_at', 'deleted_at'];

    protected static function boot()
    {
        parent::boot();
        static::saved(function ($data) {
            if (request()->hasFile('file')) {
                if ($data->image()->exists()) {
                    \App\Http\Controllers\General\ImageController::delete_single_file($data->image->image, 'app/public/uploads/ad_sponsor');
                    AppImage::where(['app_imageable_type' => 'App\Models\AdSponsor', 'app_imageable_id' => $data->id, 'image' => $data->image->image])->delete();
                }
                if(request()->file_type == 'video'){
                    $video = \App\Http\Controllers\General\ImageController::upload_single_video(request()->file, 'app/public/uploads/ad_sponsor', 'storage/uploads/ad_sponsor', 'image');
                    $data->image()->create($video + ['option' => request()->file_type]);
                }else{
                    $image = \App\Http\Controllers\General\ImageController::upload_single_file(request()->file, 'app/public/uploads/ad_sponsor');
                    $data->image()->create(['image' => $image, 'option' => request()->file_type]);
                }
            }
        });
    }

    public function delete()
    {
        if ($this->image()->exists()) {
            if (file_exists(storage_path('app/public/uploads/ad_sponsor' . "/" . $this->image->image))) {
                \App\Http\Controllers\General\ImageController::delete_single_file($this->image->image, 'app/public/uploads/ad_sponsor');
            }
            AppImage::where(['app_imageable_type' => 'App\Models\AdSponsor', 'app_imageable_id' => $this->id, 'image' => $this->image->image])->delete();
        }
        parent::delete();
    }

    public function image()
    {
        return $this->morphOne(AppImage::class, 'app_imageable');
    }

    public function sponsor()
    {
        return $this->belongsTo(Sponsor::class);
    }

    public function hidden_ad()
    {
        return $this->hasMany(HiddenAd::class);
    }

    public function getFileUrlAttribute()
    {
        if ($this->image()->exists()) {
            if (!file_exists(storage_path('app/public/uploads/ad_sponsor' . "/" . $this->image->image))) {
                return asset('storage/uploads/default.png');
            }
            return asset('storage/uploads/ad_sponsor') . '/' . $this->image->image;
        } else {
            return asset('storage/uploads/default.png');
        }
    }

    public function getThumbnailUrlAttribute()
    {
        if ($this->image()->exists()) {
            if (!file_exists(storage_path('app/public/uploads/ad_sponsor' . "/" . $this->image->cover_name))) {
                return asset('storage/uploads/default.png');
            }
            return asset('storage/uploads/ad_sponsor') . '/' . $this->image->cover_name;
        } else {
            return asset('storage/uploads/default.png');
        }
    }
}

app/Http/Controllers/Dashboard/AdController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Models\{AdSponsor, Sponsor};
use App\Http\Requests\Dashboard\Ad\AdRequest;
use Illuminate\Http\Request;

class AdController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data['ads'] = AdSponsor::latest()->paginate(200);
        return view('dashboard.ad.index', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data['sponsors'] = Sponsor::get()->pluck('name', 'id');
        return view('dashboard.ad.create', $data);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(AdRequest $request)
    {
        \DB::beginTransaction();
        try {
            $ad = AdSponsor::create(array_except($request->validated(), ['file', 'file_type']));
            \DB::commit();
        } catch (Exception $e) {
            \DB::rollback();
            dd($e);
            return redirect()->route('dashboard.client.create')
                ->with('message', trans('dash.messages.something_went_wrong_please_try_again'))
                ->with('class', 'warning')->withInput();
        }
        return redirect()->route('dashboard.ad.index')->with('class', 'success')->with('message', trans('dash.messages.added_successfully'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if (!AdSponsor::find($id)) {
            return redirect()->route('dashboard.ad.index')->with('class', 'danger')->with('message', trans('dash.messages.try_2_access_not_found_content'));
        }
        $data['sponsors'] = Sponsor::get()->pluck('name', 'id');
        $data['ad'] = AdSponsor::find($id);
        return view('dashboard.ad.edit', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(AdRequest $request, $id)
    {
        if (!AdSponsor::find($id)) {
            return redirect()->route('dashboard.ad.index')->with('class', 'danger')->with('message', trans('dash.messages.try_2_access_not_found_content'));
        }
        $ad = AdSponsor::find($id);
        $ad->update(array_except($request->validated(), ['file', 'file_type']));
        return redirect()->route('dashboard.ad.index')->with('class', 'success')->with('message', trans('dash.messages.updated_successfully'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if (!AdSponsor::find($id)) {
            $response = ['status' => 'false', 'message' => trans('dash.messages.try_2_access_not_found_content')];
            return $response;
        }
        $ad = AdSponsor::find($id)->forceDelete();
        return ['status' => 'true', 'message' => trans('dash.messages.deleted_successfully')];
    }
}

app/Http/Controllers/Dashboard/AdminController.php
<?php

namespace App\Http\Controllers\Dashboard;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use DB, Auth;
use App\Models\User;
use App\Models\Role;
use App\Http\Requests\Dashboard\Admin\AdminRequest;

class AdminController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data['admins'] = User::where('type', 'admin')->latest()->get();
        return view('dashboard.admins.index', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $this->data['roles'] = Role::get()->pluck('name', 'id');
        $this->data['last_admins'] = User::orderBy('id', 'desc')->where('type', 'admin')->take(10)->get();
        return view('dashboard.admins.create', $this->data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(AdminRequest $request)
    {
        DB::beginTransaction();
        try {
            $admin = User::create(array_except($request->validated(), ['avatar']) + ['type' => 'admin']);
            DB::commit();
        } catch (Exception $e) {
            DB::rollback();
            return redirect()->route('dashboard.admin.create')
                ->with('message', trans('dash.messages.something_went_wrong_please_try_again'))
                ->with('class', 'warning')
                ->withInput($request->validated());
        }
        return redirect()->route('dashboard.admin.index')->with('class', 'success')->with('message', trans('dash.messages.added_successfully'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    { }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if (!User::where('type', 'admin')->find($id)) {
            return redirect()->route('dashboard.admin.index')->with('class', 'danger')->with('message', trans('dash.messages.try_2_access_not_found_content'));
        }
        $this->data['admin'] = User::where('type', 'admin')->find($id);
        $this->data['roles'] = Role::get()->pluck('name', 'id');
        $this->data['last_admins'] = User::orderBy('id', 'desc')->where('type', 'admin')->take(10)->get();
        return view('dashboard.admins.edit', $this->data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(AdminRequest $request, $id)
    {
        if (!User::where('type', 'admin')->find($id)) {
            return redirect()->route('dashboard.admin.index')->with('class', 'danger')->with('message', trans('dash.messages.try_2_access_not_found_content'));
        }
        DB::beginTransaction();
        try {
            $admin = User::find($id)->update(array_except($request->validated(), ['avatar']));
            DB::commit();
        } catch (Exception $e) {
            DB::rollback();
            return redirect()->route('dashboard.admin.edit', $id)
                ->with('message', trans('dash.messages.something_went_wrong_please_try_again'))
                ->with('class', 'warning')
                ->withInput($request->validated());
        }
        return redirect()->route('dashboard.admin.index')->with('class', 'success')->with('message', trans('dash.messages.updated_successfully'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if (!User::where('type', 'admin')->find($id)) {
            $response = ['status' => 'false', 'message' => trans('dash.messages.try_2_access_not_found_content')];
            return $response;
        }
        $user = User::where('type', 'admin')->find($id);
        $user->forceDelete();
        return ['status' => 'true', 'message' => trans('dash.messages.deleted_successfully')];
    }

    public function chat()
    {
        return view('dashboard.admins.chat');
    }
}

app/Http/Controllers/Dashboard/AuthController.php
<?php

namespace App\Http\Controllers\Dashboard;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\User;
use Hash;
use App\Http\Requests\Dashboard\Auth\UpdateProfileData;
use App\Http\Requests\Dashboard\Auth\UpdatePassword;

class AuthController extends Controller
{
    public function signin_view()
    {
        return view('dashboard.auth.login');
    }

    public function signin(Request $request)
    {
        if ($request->email && $request->password) {
            if (auth()->attempt(['email' => $request->email, 'password' => $request->password, 'type' => 'admin'], true)) {
                return redirect()->route('dashboard.home');
            } else {
                $request->session()->flash('warning', trans('dashboard.email_or_password_invalid'));
                return redirect()->route('dashboard.login')
                    ->with('message', trans('dash.messages.data_invalid'))
                    ->with('class', 'danger');
            }
        } else {
            return redirect()->route('dashboard.login')
                ->with('message', trans('dash.messages.data_not_completed'))
                ->with('class', 'danger');
        }
    }

    public function signout()
    {
        auth()->logout();
        return redirect()->route('dashboard.login')
            ->with('message', trans('dash.messages.logged_out_successfully'))
            ->with('class', 'success');
    }

    public function profile()
    {
        return view('dashboard.auth.profile');
    }

    public function update(UpdateProfileData $request)
    {
        User::find(auth()->id())->update(array_except($request->validated(), ['avatar']));
        return redirect()->route('dashboard.admin.profile')->with('class', 'success')->with('message', trans('dash.messages.updated_successfully'));
    }

    public function update_password(UpdatePassword $request)
    {
        if (Hash::check($request->old_password, auth()->user()->getAuthPassword())) {
            User::find(auth()->id())->update(['password' => $request->password]);
            return redirect()->route('dashboard.admin.profile')->with('class', 'success')->with('message', trans('dash.messages.updated_password_successfully'));
        } else {
            return back()->with('message', trans('dash.messages.wrong_password'))->with('class', 'danger');
        }
    }
}

app/Http/Controllers/Dashboard/PostController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\{Post};

class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $data['posts'] = Post::when($request->activity, function ($q) use ($request) {
                $q->whereActivityType($request->activity);
            })->latest()->paginate(20);
        return view('dashboard.post.index', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        if (!Post::find($id)) {
            return redirect()->route('dashboard.post.index')->with('class', 'danger')->with('message', trans('dash.messages.try_2_access_not_found_content'));
        }
        $data['post'] = Post::find($id);
        return view('dashboard.post.show', $data);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if (!Post::find($id)) {
            $response = ['status' => 'false', 'message' => trans('dash.messages.try_2_access_not_found_content')];
            return $response;
        }
        $post = Post::find($id)->forceDelete();
        return ['status' => 'true', 'message' => trans('dash.messages.deleted_successfully')];
    }
}

app/Http/Controllers/Dashboard/SupportController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class SupportController extends Controller
{
    //
}

resources/views/dashboard/ad/create.blade.php
@extends('dashboard.layout')

@section('page_title')
{{ trans('dash.ad.add_new_ad') }}
@endsection
@section('sidebar_title')
    <a href="{{ route('dashboard.ad.index') }}" class="breadcrumb-item">{{ trans('dash.ad.ads') }}</a>
    <span class="breadcrumb-item active">{{ trans('dash.ad.add_new_ad') }}</span>
@endsection
@section('content')
        <div class="card">
            <div class="card-header header-elements-inline">
                <h5 class="card-title">{{ trans('dash.ad.ad_data') }}</h5>
            </div>
            <div class="card-body">
                {!! Form::open(['route' => 'dashboard.ad.store' , 'method' => "POST" , 'files' => true , 'data-fouc']) !!}
                    @include('dashboard.ad.form')
				{!! Form::close() !!}
            </div>
        </div>
@endsection

resources/views/dashboard/ad/edit.blade.php
@extends('dashboard.layout')

@section('page_title')
    {{ trans('dash.ad.edit_ad_data') }}
@endsection
@section('sidebar_title')
    <a href="{{ route('dashboard.ad.index') }}" class="breadcrumb-item">{{ trans('dash.ad.ads') }}</a>
    <span class="breadcrumb-item active">{{ trans('dash.ad.edit_ad_data') }}</span>
@endsection
@section('content')
        <div class="card">
            <div class="card-header header-elements-inline">
                <h5 class="card-title">{{ trans('dash.ad.edit_ad_data') }} : {{ $ad->name }}</h5>
            </div>
            <div class="card-body">
                {!! Form::model($ad, ['route' => ['dashboard.ad.update', $ad->id] , 'method' => "PUT" , 'files' => true , 'data-fouc']) !!}
                    @include('dashboard.ad.form')
				{!! Form::close() !!}
            </div>
        </div>
@endsection

resources/views/dashboard/ad/index.blade.php
@extends('dashboard.layout')
@section('file_scripts')
    <script src="{{ asset('assets/global') }}/js/plugins/media/fancybox.min.js"></script>
    <script src="{{ asset('assets/global') }}/js/plugins/forms/styling/uniform.min.js"></script>
    <script src="{{ asset('assets/global') }}/js/plugins/tables/datatables/datatables.min.js"></script>
    <script src="{{ asset('assets/global') }}/js/plugins/tables/datatables/extensions/buttons.min.js"></script>
    <script src="{{ asset('assets/global') }}/js/plugins/forms/selects/select2.min.js"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
@endsection

@section('custom_scripts')
    <script src="{{ asset('assets/global') }}/js/demo_pages/datatables_extension_buttons_init.js"></script>
    <script src="{{ asset('assets/global') }}/js/demo_pages/gallery_library.js"></script>
@endsection
@section('page_title')
    {{ trans('dash.ad.ads') }}
@endsection
@section('sidebar_title')
    <span class="breadcrumb-item active">{{ trans('dash.ad.ads') }}</span>
@endsection
@section('content')
    <div class="card">
        <div class="card-header header-elements-inline">
            <h5 class="card-title">{{ trans('dash.ad.ads') }}</h5>
            <div class="header-elements">
                <div class="list-icons">
                    <a href="{{ route('dashboard.ad.create') }}"
                       class="btn btn-success btn-labeled btn-labeled-left"><b><i
                                class="icon-plus2"></i></b>{{ trans('dash.ad.add_new_ad') }}</a>
                </div>
            </div>
        </div>
        <div class="card-body">
            <div class="d-flex justify-content-center">
                {!! $ads->links() !!}
            </div>
            <table class="table datatable-button-init-basic">
                <thead>
                <tr class="text-center">
                    <th>#</th>
                    <th>{{ trans('dash.ad.ad') }}</th>
                    <th>{{ trans('dash.sponsor.sponsor') }}</th>
                    <th>{{ trans('dash.ad.start_date') }}</th>
                    <th>{{ trans('dash.ad.end_date') }}</th>
                    <th>{{ trans('dash.ad.visit_ad') }}</th>
                    <th>{{ trans('dash.ad.desc') }}</th>
                    <th>{{ trans('dash.table.created_at') }}</th>
                    <th>{{ trans('dash.table.action') }}</th>
                </tr>
                </thead>
                <tbody>
                @foreach($ads as $ad)
                    <tr class="text-center" id="row_{{ $ad->id }}">
                        <td>{{ $loop->iteration }}</td>
                        <td>
                            @if($ad->image->option == 'image')
                                <a href="{{ $ad->file_url }}" data-popup="lightbox">
                                    <img src="{{ $ad->file_url }}" alt="" class="img-preview rounded">
                                </a>
                            @elseif($ad->image->option == 'video')
                                <div style="width: 150px" class="card-img embed-responsive embed-responsive-16by9">
                                    <video style="width: 100%; height:100px" controls>
                                        <source src="{{ $ad->file_url }}" type="video/mp4">
                                        <source src="{{ $ad->file_url }}" type="video/ogg">
                                        Your browser does not support HTML video.
                                    </video>
                                </div>
                        @endif
                        <td>{{ $ad->sponsor->name }}</td>
                        <td>
                            {{ $ad->start_date }}
                        </td>
                        <td>
                            {{ $ad->end_date }}
                        </td>
                        <td>
                            <a href="{{ $ad->url  }}" target="_blank">{{ trans('dash.ad.visit_ad') }}</a>
                        </td>
                        <td>
                            <span class="badge bg-success badge-pill">{{ str_limit($ad->desc, 50) }}</span>
                        </td>
                        <td>{{ $ad->created_at->diffforHumans() }}</td>
                        <td>
                            <div class="list-icons">
                                <div class="list-icons-item dropdown">
                                    <a href="#" class="list-icons-item caret-0 dropdown-toggle" data-toggle="dropdown">
                                        <i class="icon-menu9"></i>
                                    </a>
                                    <div class="dropdown-menu dropdown-menu-right">
                                        <a href="{{ route('dashboard.ad.edit', $ad->id) }}"
                                           class="dropdown-item"><i
                                                class="icon-pencil7"></i>{{ trans('dash.actions.edit') }}</a>
                                        <div class="dropdown-divider"></div>
                                        <a onclick="sweet_delete('{{ route('dashboard.ad.destroy', $ad->id) }}', {{ $ad->id }})"
                                           class="dropdown-item"><i
                                                class="icon-bin"></i>{{ trans('dash.actions.delete') }}</a>
                                    </div>
                                </div>
                            </div>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
            <div class="d-flex justify-content-center">
                {!! $ads->links() !!}
            </div>
        </div>
    </div>
    @include('dashboard.parts.delete_alert')
@endsection

resources/views/dashboard/ad/last_created.blade.php
<div class="col-md-5">
    <div class="card">
        <div class="card-header header-elements-inline">
            <h5 class="card-title">{{ trans('dash.package.latest_packages') }}</h5>
        </div>
        <table class="table datatable-basic">
            <thead>
                <tr class="text-center">
                    <th>#</th>
                    <th>{{ trans('dash.package.name') }}</th>
                    <th>{{ trans('dash.table.created_at') }}</th>
                </tr>
            </thead>
            <tbody>
                @foreach($latest_packages as $package)
                    <tr class="text-center">
                        <td>{{ $loop->iteration }}</td>
                        <td>{{ $package->name }}</td>
                        <td>{{ $package->created_at->diffforHumans() }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>
</div>